const products = [
    {
        id: "a1b2c3d4-e5f6-g7h8-i9j0-k1l2m3n4o5p6",
        is_favorite: true,
        is_rental: true,
        type: 'HANDHELD_COMPUTER',
        manufacturer: 'ZEBRA',
        operational_area: [
            { label: 'Warehouse & Production', value: 'WAREHOUSE_&_PRODUCTION' }
        ],
        price: 370,
        weight: 236,
        name: 'Zebra TC21/26',
        image: 'https://skystatic08.atmos.id/11018/2049634327/2002200717/2012441964/zebra_tc21@2x.jpg',
        specifications: [
            'Price: from 370 euros',
            'Display: 5 inches',
            'Weight: 236 grams',
            'Available accessories: Scanner: 1D and 2D barcodes, replaceable 3,100 mAh battery, extended 5,400 mAh battery possible'
        ],
        assessment: 'The TC21 (WLAN version) or the TC26 (with mobile phone option) is the entry-level device with an imager for simple applications in warehouse, production or delivery. The improved optional handle now also allows use of the rear camera. TC26 also communicates via mobile communications and is therefore interesting for outdoor use.',
        manufacturer_url: 'https://www.zebra.com/de/de/products/mobile-computers/handheld/tc21-tc26.html',
    },
    {
        id: "b2c3d4e5-f6g7-h8i9-j0k1-l2m3n4o5p6q",
        is_favorite: true,
        is_rental: true,
        type: 'HANDHELD_COMPUTER',
        manufacturer: 'ZEBRA',
        operational_area: [
            { label: 'Warehouse & Production', value: 'WAREHOUSE_&_PRODUCTION' },
            { label: 'Field Service', value: 'FIELD_SERVICE' }
        ],
        price: 1100,
        weight: 445,
        name: 'Zebra MC3300X',
        image: 'https://skystatic08.atmos.id/11018/2049634327/2003088216/2012441964/zebra_mc3300@2x.jpeg',
        specifications: [
            'Price: from 1100 euros',
            'Display: 4 inches',
            'Weight: 445 grams',
            'Available accessories: various engines - very powerful 2D imager, configuration with pistol grip, rotating head, 0° or 45° scan'
        ],
        assessment: 'The top device in the mid-range storage class with a large display and full keyboard. Auto-Range Imager enables multiple scans and scans up to 21 m away.',
        manufacturer_url: 'https://www.zebra.com/de/de/products/mobile-computers/handheld/mc3300.html',
    },
    {
        id: "c3d4e5f6-g7h8-i9j0-k1l2-m3n4o5p6q7r",
        is_favorite: true,
        is_rental: true,
        type: 'HANDHELD_COMPUTER',
        manufacturer: 'ZEBRA',
        operational_area: [
            { label: 'Warehouse & Production', value: 'WAREHOUSE_&_PRODUCTION' },
            { label: 'Field Service', value: 'FIELD_SERVICE' }
        ],
        price: 1400,
        weight: 266,
        name: 'Zebra TC52ax',
        image: 'https://skystatic08.atmos.id/11018/2049634327/2083848334/2012441964/TC52ax.png',
        specifications: [
            'Price: from 1400 euros',
            'Display: 5 inches',
            'Weight: 266 grams',
            'Available accessories: 1D and 2D barcodes (Imager SE4720), battery for up to 14 h shifts, hot swap possible, IP68, BT 5.1, WIFI-6, optional SE5500 scanner up to 12 m range, upgradeable to Android 14'
        ],
        assessment: 'A robust and technically very well-equipped device with a good scan engine. A plus are the 6 programmable buttons on the sides of the display.',
        manufacturer_url: 'https://www.zebra.com/de/de/products/spec-sheets/mobile-computers/handheld/tc5x-series.html',
    },
    {
        id: "d4e5f6g7-h8i9-j0k1-l2m3-n4o5p6q7r8s",
        is_favorite: true,
        is_rental: true,
        type: 'HANDHELD_COMPUTER',
        manufacturer: 'ZEBRA',
        operational_area: [
            { label: 'Warehouse & Production', value: 'WAREHOUSE_&_PRODUCTION' },
            { label: 'Field Service', value: 'FIELD_SERVICE' }
        ],
        price: 1250,
        weight: 249,
        name: 'Zebra TC57x',
        image: 'https://skystatic08.atmos.id/11018/2049634327/2097486652/2012441964/zebra_tc57@2x.jpg',
        specifications: [
            'Price: from 1250 euros',
            'Display: 5 inches',
            'Weight: 249 grams',
            'Available accessories: 1D and 2D barcodes (Imager SE4710), battery for up to 14 h shifts, hot swap possible, LTE, IP68, BT 5.0'
        ],
        assessment: 'The robust TC57x complements the functionality of the TC52x with mobile radio capability. This means that the device can be used in external warehouses or field service.',
        manufacturer_url: 'https://www.zebra.com/de/de/products/mobile-computers/handheld/tc52-tc57-series-touch-computer.html',
    },
    {
        id: "e5f6g7h8-i9j0-k1l2-m3n4-o5p6q7r8s9t",
        is_favorite: false,
        is_rental: false,
        type: 'HANDHELD_COMPUTER',
        manufacturer: 'CASIO',
        operational_area: [
            { label: 'Warehouse & Production', value: 'WAREHOUSE_&_PRODUCTION' },
        ],
        price: 900,
        weight: 260,
        name: 'Casio DT-X450',
        image: 'https://skystatic08.atmos.id/11018/2049634327/2003011650/2012441964/casio_dt-x400@2x.png',
        specifications: [
            'Price: from 900 euros',
            'Display: 3.2 inches',
            'Weight: 260 grams',
            'Available accessories: Freely assignable function keys, 25 hours of continuous operation, LTE, Android 11, 3 m fall resistant'
        ],
        assessment: 'With the DT-X400 series, Casio is bringing its first Android devices onto the market. The device sits comfortably in the hand thanks to the well thought-out handle and rubberized surface. The touch display is a bit small, but fans of keyboard-based input will get their money\'s worth.',
        manufacturer_url: 'https://www.casio-europe.com/de/produkte/mobile-datenerfassung/dt-x400/',
    },
    {
        id: "f6g7h8i9-j0k1-l2m3-n4o5-p6q7r8s9t0u",
        is_favorite: false,
        is_rental: false,
        type: 'SMARTPHONE',
        manufacturer: 'CAT',
        operational_area: [
            { label: 'Beverage Logistics', value: 'BEVERAGE_LOGISTICS' },
        ],
        price: 370,
        weight: 320,
        name: 'CAT S53',
        image: 'https://skystatic08.atmos.id/11018/2049634327/2003436729/2012441964/CAT S53.png',
        specifications: [
            'Price: from 370 euros',
            'Display: 6.5 inches',
            'Weight: 320 grams',
            'Available accessories: 5500 mAh battery with quick charging function, dual SIM capable, 1.8 m drop-proof, 48 MP camera, IP68, IP69K & MIL-SPEC 810H, extra internal flashlight'
        ],
        assessment: 'Modern and robust: The device is more powerful than its predecessors and has Android 11, 6 GB of RAM and 128 GB of storage. It should be noted that the screen brightness still needs improvement in direct sunlight.',
        manufacturer_url: 'https://www.catphones.com/de-de/cat-s53/',
    },
    {
        id: "d9b6cff8-0493-416d-b430-3440297b7580",
        is_favorite: true,
        is_rental: false,
        type: 'FORKLIFT_TERMINAL_TABLET',
        manufacturer: 'ZEBRA',
        operational_area: [
            { label: 'Maintenance', value: 'MAINTENANCE' },
            { label: 'Warehouse & Production', value: 'WAREHOUSE_&_PRODUCTION' }, 
            { label: 'Field Service', value: 'FIELD_SERVICE' }, 
        ],
        price: 620,
        weight: 690,
        name: 'Zebra ET40/45',
        image: 'https://skystatic08.atmos.id/11018/2049634327/2004413200/2012441964/Zebra ET45_ET40.png',
        specifications: [
            'Price: from 620 euros',
            'Display: 10 inches',
            'Weight: 690 grams',
            'Available accessories: SE4100, SE4710 or SE55 1D/2D extended range scanning module, 4 or 8 GB RAM, support up to Android 14, Wi-FI 6, 5G (ET45), 8"/10" (optional), IP65, 7600mAh removable battery'
        ],
        assessment: 'The Zebra ET40 and Zebra ET45 are modern rugged tablets for indoor and outdoor use. Both tablets are available in 8" or 10" and are very robust. Both models also contain the latest hardware and software, with a scanner and, with the ET45, also mobile communications up to 5G.',
        manufacturer_url: 'https://www.zebra.com/de/de/products/spec-sheets/tablets/et40-et45.html',
    },
    {
        id: "55c70f89-d4a4-4d12-abd5-df2dd73c8f78",
        is_favorite: false,
        is_rental: false,
        type: 'HANDHELD_COMPUTER',
        manufacturer: 'DATALOGIC',
        operational_area: [
            { label: 'Warehouse & Production', value: 'WAREHOUSE_&_PRODUCTION' },
            { label: 'Field Service', value: 'FIELD_SERVICE' }
        ],
        price: 800,
        weight: 285,
        name: 'Datalogic memor 11',
        image: 'https://skystatic08.atmos.id/11018/2049634327/2004895232/2012441964/datalogic_memor10@2x.jpg',
        specifications: [
            'Price: from 800 euros',
            'Display: 5 inches',
            'Weight: 285 grams',
            'Available accessories: 1D/2D imager with Green Spot technology (visual scan confirmation), contactless charging possible - replaceable battery, upgradeable to Android 14, mobile radio optional, IP65'
        ],
        assessment: 'The Memor 11 from Datalogic is a high-performance device for warehouse and field service applications. The technical parameters are convincing, the Android system is up to date. The device competes in its class against the CT60XP from Honeywell or the TC52x from Zebra.',
        manufacturer_url: 'https://www.datalogic.com/deu/einzelhandel-industrielle-automation-transport-logistik-gesundheitswesen-weitere-anwendungen/mobilcomputer/memor-11-pd-934.html',
    },
    {
        id: "11db3ca5-3eb6-4b6d-8f50-f4c383d23da3",
        is_favorite: false,
        is_rental: false,
        type: 'WEARABLE_HANDHELD_SCANNER',
        manufacturer: 'POINT_MOBILE',
        operational_area: [
            { label: 'Warehouse & Production', value: 'WAREHOUSE_&_PRODUCTION' },
        ],
        price: 600,
        weight: 49,
        name: 'Point Mobile PM5',
        image: 'https://skystatic08.atmos.id/11018/2049634327/2012518994/2012441964/Point Mobile PM5.png',
        specifications: [
            'Price: from 600 euros',
            'Display: 0 inches',
            'Weight: 49 grams',
            'Available accessories: Honeywell N6703 Ultra slim 1D/2D Barcode Scan Engine, 510mAh (Standard), 700mAh (Optional), IP65, Bluetooth, NFC'
        ],
        assessment: 'The Point Mobile PM5 is a compact and lightweight ring scanner. It impresses with high scanning performance and speed. The battery lasts 9 hours as standard; The operating time can be extended with an additional battery',
        manufacturer_url: 'https://www.pointmobile.com/de/products-mobilecomputers/PM5',
    },
    {
        id: "8e84c6de-9943-4822-870d-198cba02ac43",
        is_favorite: false,
        is_rental: false,
        type: 'HANDHELD_COMPUTER',
        manufacturer: 'ZEBRA',
        operational_area: [
            { label: 'Beverage Logistics', value: 'BEVERAGE_LOGISTICS' }, 
            { label: 'Warehouse & Production', value: 'WAREHOUSE_&_PRODUCTION' },
        ],
        price: 560,
        weight: 296,
        name: 'Zebra MC2700',
        image: 'https://skystatic08.atmos.id/11018/2049634327/2012669047/2012441964/ZebraMC2700.png',
        specifications: [
            'Price: from 560 euros',
            'Display: 4 inches',
            'Weight: 296 grams',
            'Available accessories: Standard range 1D/2D scan engine and removable battery, expandable to 4,900 mAh'
        ],
        assessment: 'The latest device class from Zebra is a comparatively inexpensive device with good performance features - depending on the model variant - and a 34-key hardware keyboard. New is the “PRZM Intelligent Imaging” technology, which can also be used to read damaged barcodes. Thanks to its cellular capability, the MC2700 is suitable for outdoor use.',
        manufacturer_url: 'https://www.zebra.com/de/de/products/spec-sheets/mobile-computers/handheld/mc2200-mc2700.html',
    },
    {
        id: "5b6ef15b-b61a-47f5-b2f4-aa6f13be337d",
        is_favorite: false,
        is_rental: false,
        type: 'WEARABLE_HANDHELD_SCANNER',
        manufacturer: 'ZEBRA',
        operational_area: [
            { label: 'Warehouse & Production', value: 'WAREHOUSE_&_PRODUCTION' },
        ],
        price: 700,
        weight: 70,
        name: 'Zebra RS6100',
        image: 'https://skystatic08.atmos.id/11018/2049634327/2015395946/2012441964/Zebra RS6100.png',
        specifications: [
            'Price: from 700 euros',
            'Display: 0 inches',
            'Weight: 70 grams',
            'Available accessories: Powerful 1D/2D scanning module SE55, pairing with Zebra devices via NFC or BT 5.2, replaceable battery'
        ],
        assessment: 'The RS6100 ring scanner from Zebra is a tool for scan-intensive processes in warehouse logistics. The wearable can be worn on a finger, mounted on a glove, on the back of the hand or on a collar. With the new scanning module, a range of 12m can be achieved.',
        manufacturer_url: 'https://www.zebra.com/de/de/products/mobile-computers/wearable-computers/rs6100.html',
    },
    {
        id: "fa95eb6c-e269-462e-8418-cb6f647eb54b",
        is_favorite: false,
        is_rental: false,
        type: 'SMARTPHONE',
        manufacturer: 'POINT_MOBILE',
        operational_area: [
            { label: 'Beverage Logistics', value: 'BEVERAGE_LOGISTICS' }, 
            { label: 'Warehouse & Production', value: 'WAREHOUSE_&_PRODUCTION' },
        ],
        price: 550,
        weight: 246,
        name: 'Point Mobile PM75',
        image: 'https://skystatic08.atmos.id/11018/2049634327/2015462482/2012441964/PointMobilePM75.png',
        specifications: [
            'Price: from 550 euros',
            'Display: 5.45 inches',
            'Weight: 246 grams',
            'Available accessories: 5,800mAh extra battery, Android 11, IP65, LTE, N3601 or N6603 1D/2D barcode scanning engine'
        ],
        assessment: 'The PM75 comes with the latest equipment and software. It is a very practical device that can be used in a variety of ways and for a relatively affordable price. The choice between two high-quality Honeywell scan engines and an extra additional battery is an advantage here.',
        manufacturer_url: 'https://www.pointmobile.com/de/products-mobilecomputers/PM75',
    },
    {
        id: "df8d9700-ee14-4102-892d-259a72a023d9",
        is_favorite: false,
        is_rental: false,
        type: 'HANDHELD_COMPUTER',
        manufacturer: 'CIPHERLAB',
        operational_area: [
            { label: 'Maintenance', value: 'MAINTENANCE' },
            { label: 'Warehouse & Production', value: 'WAREHOUSE_&_PRODUCTION' },
        ],
        price: 850,
        weight: 288,
        name: 'Cipherlab RS36',
        image: 'https://skystatic08.atmos.id/11018/2049634327/2016244565/2012441964/Cipherlab RS36.png',
        specifications: [
            'Price: from 850 euros',
            'Display: 5.5 inches',
            'Weight: 288 grams',
            'Available accessories: 1D/2D midrange/longrange imager, standard 4000 mAh (12 h+) battery, 6000 mAh (18 h+) extended battery, upgradeable to Android 14, optional pistol grip and RFID reader, IP 68, LTE capable'
        ],
        assessment: 'Robust mid-range touch computer. The device is offered with optional scan engines for different purposes. Programmable function keys enable individual optimizations. Striking thanks to its strong battery performance and a scanning range of up to 12 m. An alternative to the established manufacturers.',
        manufacturer_url: 'https://www.cipherlab.com/de/product-283440/Mobiler-Computer-mit-Touchscreen-RS36-Series.html',
    },
    {
        id: "c1dc2cf5-a1f6-49be-a533-066a3d075310",
        is_favorite: true,
        is_rental: false,
        type: 'WEARABLE_HANDHELD_SCANNER',
        manufacturer: 'ZEBRA',
        operational_area: [
            { label: 'Maintenance', value: 'MAINTENANCE' },
            { label: 'Warehouse & Production', value: 'WAREHOUSE_&_PRODUCTION' },
        ],
        price: 1400,
        weight: 134,
        name: 'Zebra WS50',
        image: 'https://skystatic08.atmos.id/11018/2049634327/2016631942/2012441964/zebra ws50.png',
        specifications: [
            'Price: from 1400 euros',
            'Display: 2 inches',
            'Weight: 134 grams',
            'Available accessories: 1,300 mAh battery, hot swap, IP65, SE4770 1D/2D imager, WLAN, BT, NFC, Android 11 AOSP, modular'
        ],
        assessment: 'Zebra demonstrates its innovative strength when it comes to mobile computers with the robust wearable computer WS50. The device combines a mobile handheld computer and wearable scanner in one device. The WS50 is flexible in terms of portability, as it can be worn on the finger, on the back of the hand or on the wrist.',
        manufacturer_url: 'https://www.zebra.com/de/de/products/spec-sheets/mobile-computers/wearable/ws50.html',
    },
    {
        id: "67d80ceb-9f2f-4c81-b973-28923fa556f4",
        is_favorite: false,
        is_rental: false,
        type: 'WEARABLE_HANDHELD_SCANNER',
        manufacturer: 'ACD',
        operational_area: [
            { label: 'Warehouse & Production', value: 'WAREHOUSE_&_PRODUCTION' },
        ],
        price: 350,
        weight: 45,
        name: 'ACD HasciSE',
        image: 'https://skystatic08.atmos.id/11018/2049634327/2017010790/2012441964/ACD HasciSE.png',
        specifications: [
            'Price: from 350 euros',
            'Display: 0 inches',
            'Weight: 45 grams',
            'Available accessories: IP54, 7500 scans per charge, 1D and 2D imager Zebra SE4710, Bluetooth 4.0'
        ],
        assessment: 'The HasciSE is ideal for work processes in which both hands are used without fatigue. The scanner module is lightweight and can be attached to a wrist cuff, glove or retractable spool. It is also robust and therefore fits perfectly into industrial environments.',
        manufacturer_url: 'https://www.acd-gruppe.de/news/hascise-der-beste-ergonomische-handrueckenscanner-in-industriequalitaet/',
    },
    {
        id: "5e650805-6707-4a39-8c2c-d9bb523b93ca",
        is_favorite: true,
        is_rental: false,
        type: 'HANDHELD_COMPUTER',
        manufacturer: 'CASIO',
        operational_area: [
            { label: 'Beverage Logistics', value: 'BEVERAGE_LOGISTICS' },
            { label: 'Warehouse & Production', value: 'WAREHOUSE_&_PRODUCTION' },
            { label: 'Field Service', value: 'FIELD_SERVICE' }
        ],
        price: 700,
        weight: 240,
        name: 'Casio ET-L10',
        image: 'https://skystatic08.atmos.id/11018/2049634327/2017181285/2012441964/casio_et_l10@2x.jpg',
        specifications: [
            'Price: from 700 euros',
            'Display: 5.7 inches',
            'Weight: 240 grams',
            'Available accessories: 1D and 2D imager and NFC, battery change possible by manufacturer'
        ],
        assessment: 'With the ET-L10, Casio delivers a light, robust handheld with an integrated scanner. The smartphone-like device is very powerful and the large display is very user-friendly for a handheld. It could be used in deliveries, for example, or for less robust activities in warehouse logistics.',
        manufacturer_url: 'https://www.mobile-barcode-scanner.com/de/produkte/et-l10/#spezifikationen',
    },
    {
        id: "a819fb90-2597-4f6e-beb7-85f548f92be7",
        is_favorite: false,
        is_rental: false,
        type: 'FORKLIFT_TERMINAL_TABLET',
        manufacturer: 'HONEYWELL',
        operational_area: [
            { label: 'Maintenance', value: 'MAINTENANCE' },
            { label: 'Warehouse & Production', value: 'WAREHOUSE_&_PRODUCTION' },
            { label: 'Field Service', value: 'FIELD_SERVICE' }
        ],
        price: 800,
        weight: 674,
        name: 'Honeywell ScanPal EDA10A',
        image: 'https://skystatic08.atmos.id/11018/2049634327/2017246317/2012441964/Honeywell ScanPal EDA10A.png',
        specifications: [
            'Price: from 800 euros',
            'Display: 10.1 inches',
            'Weight: 674 grams',
            'Available accessories: WIFI-6, 5G, 1.3 m fall resistant, BT, integrated barcode scanner (S0703 Slim Imager), IP65, upgradeable to Android 14 version, 12 hour usage time, accessories such as shoulder strap, shoulder bag, VESA mounting plate, stylus, Vehicle dock available'
        ],
        assessment: 'Honeywell has been impressing with reliable handhelds for a long time and is launching a convincing model for tablet industrial devices with the ScanPal EDA10A. It\'s slim, modern and the display is easy to read in sunlight with 550 nits screen brightness. Thanks to numerous accessories and an integrated scan engine, the robust tablet can be used in a variety of ways.',
        manufacturer_url: 'https://sps.honeywell.com/de/de/products/productivity/mobile-computers/tablets/scanpal-eda10a-tablet',
    },
    {
        id: "84749378-7a03-4a4b-bd54-dcc41a4a6150",
        is_favorite: false,
        is_rental: false,
        type: 'SMARTPHONE',
        manufacturer: 'POINT_MOBILE',
        operational_area: [
            { label: 'Beverage Logistics', value: 'BEVERAGE_LOGISTICS' },
            { label: 'Warehouse & Production', value: 'WAREHOUSE_&_PRODUCTION' },
            { label: 'Field Service', value: 'FIELD_SERVICE' }
        ],
        price: 650,
        weight: 165,
        name: 'Point Mobile PM30',
        image: 'https://skystatic08.atmos.id/11018/2049634327/2017832970/2012441964/ponit_mobilePM30.png',
        specifications: [
            'Price: from 650 euros',
            'Display: 4.7 inches',
            'Weight: 165 grams',
            'Available accessories: extra battery (optional) 6,500mAh, 2D Imager Honeywell Ultra-Slim Engine, IP67, LTE, WLAN, BT'
        ],
        assessment: 'The PM30 is a cost-effective industrial smartphone from Point Mobile. It has new software and hardware, which is sufficient for many activities. The expandable battery is a positive thing here, which means the runtime can be very good. Despite the rather lower price, the device is robust and well protected against dust and water.',
        manufacturer_url: 'https://www.pointmobile.com/de/products-mobilecomputers/PM30',
    },
    {
        id: "b4e38334-1cde-4146-b579-406d2c7c7a83",
        is_favorite: true,
        is_rental: false,
        type: 'SMARTPHONE',
        manufacturer: 'SAMSUNG',
        operational_area: [
            { label: 'Beverage Logistics', value: 'BEVERAGE_LOGISTICS' },
        ],
        price: 200,
        weight: 172,
        name: 'Samsung Xcover 5',
        image: 'https://skystatic08.atmos.id/11018/2049634327/2018426427/2012441964/Samsung Xcover 5.png',
        specifications: [
            'Price: from 200 euros',
            'Display: 5.3 inches',
            'Weight: 172 grams',
            'Available accessories: Outdoor smartphone with protection class IP68 and replaceable battery'
        ],
        assessment: 'If you are looking for a simple and sufficiently robust mobile device and can do without a scanning function, the Xcover 5 from Samsung is a good choice. The device offers a very good price-performance ratio.',
        manufacturer_url: 'https://www.samsung.com/de/smartphones/others/galaxy-xcover-5-black-64gb-sm-g525fzkdeeb/',
    },
    {
        id: "7bbd7bd2-60f3-4824-9bec-4810cf116dd2",
        is_favorite: false,
        is_rental: false,
        type: 'HANDHELD_COMPUTER',
        manufacturer: 'I_SAFE_MOBILE',
        operational_area: [
            { label: 'Warehouse & Production', value: 'WAREHOUSE_&_PRODUCTION' },
            { label: 'Explosion-proof', value: 'EXPLOSION_PROOF' },
        ],
        price: 1600,
        weight: 325,
        name: 'i.Safe Mobile IS530.1',
        image: 'https://skystatic08.atmos.id/11018/2049634327/2018904232/2012441964/i.Safe IS530.1 mit Pistolengriff.png',
        specifications: [
            'Price: from 1600 euros',
            'Display: 4.5 inches',
            'Weight: 325 grams',
            'Available accessories: Explosion-proof, IP68, replaceable battery, additionally available pistol grip with Zebra scan engine (1D and 2D barcodes) at close range up to 6 meters or distances over 15 meters'
        ],
        assessment: 'The powerful industrial smartphone can be used in a variety of ways thanks to the ISM interface. Various additional modules and the extremely high resistance make it a unique, high-performance multifunctional device, especially for the chemical industry.',
        manufacturer_url: 'https://www.isafe-mobile.com/de/produkte/produkte-zone-1/21/is5301',
    },
    {
        id: "fe6ca295-232a-4314-b6b8-8caec74bf13e",
        is_favorite: false,
        is_rental: false,
        type: 'HANDHELD_COMPUTER',
        manufacturer: 'HONEYWELL',
        operational_area: [
            { label: 'Beverage Logistics', value: 'BEVERAGE_LOGISTICS' },
            { label: 'Warehouse & Production', value: 'WAREHOUSE_&_PRODUCTION' },
        ],
        price: 1000,
        weight: 460,
        name: 'Honeywell ScanPal EDA61K',
        image: 'https://skystatic08.atmos.id/11018/2049634327/2020025177/2012441964/honeywell_scanpal_eda61k@2x.jpg',
        specifications: [
            'Price: from 1000 euros',
            'Display: 4 inches',
            'Weight: 460 grams',
            'Available accessories: 2 scan engines selectable for scanning in the close range (a few centimeters) or long range (up to 15 meters), 7,000 mAh battery for up to 25 hours of operating time'
        ],
        assessment: 'The EDA61K from the Scanpal series - for small and medium-sized companies. In addition to the powerful EX20 long-range scan engine, LTE is supported so that it can be used in an outdoor warehouse without WiFi coverage. The 34 or 47 key keyboard supports data collection in harsh environments.',
        manufacturer_url: 'https://www.honeywellaidc.com/de-de/products/computer-devices/handheld/scanpaleda61k',
    },
    {
        id: "f4a40cbd-4811-44e3-8a3b-ef6f191b7329",
        is_favorite: true,
        is_rental: false,
        type: 'FORKLIFT_TERMINAL_TABLET',
        manufacturer: 'SAMSUNG',
        operational_area: [
            { label: 'Maintenance', value: 'MAINTENANCE' },
            { label: 'Field Service', value: 'FIELD_SERVICE' }
        ],
        price: 500,
        weight: 429,
        name: 'Samsung Tab Active 3',
        image: 'https://skystatic08.atmos.id/11018/2049634327/2022407552/2012441964/Samsung Tab Active 3.png',
        specifications: [
            'Price: from 500 euros',
            'Display: 8 inches',
            'Weight: 429 grams',
            'Available accessories: IP68 certified and replaceable 5,050 mAh battery'
        ],
        assessment: 'Samsung\'s Tab Active 3 is a rugged, enterprise edition tablet designed for use in harsh, humid and dirty environments. In addition to the touchscreen (can be used with gloves), operation can also be done with the included stylus pen. The device is designed for vertical app operation - the physical Android control buttons are mounted vertically on the device.',
        manufacturer_url: 'https://www.samsung.com/at/business/tablets/galaxy-tab-active3-enterprise-edition-t575/sm-t575nzkaeeb/',
    },
    {
        id: "68e89cc6-d08e-471d-85a7-784eea1b6ec5",
        is_favorite: false,
        is_rental: false,
        type: 'WEARABLE_HANDHELD_SCANNER',
        manufacturer: 'PROGLOVE',
        operational_area: [
            { label: 'Warehouse & Production', value: 'WAREHOUSE_&_PRODUCTION' }
        ],
        price: 1000,
        weight: 40,
        name: 'ProGlove MARK 3',
        image: 'https://skystatic08.atmos.id/11018/2049634327/2023937341/2012441964/ProGlove MARK 3.png',
        specifications: [
            'Price: from 1000 euros',
            'Display: 0 inches',
            'Weight: 40 grams',
            'Available accessories: Multi-range scanner (10 cm - 600 cm scanning range), communication via Bluetooth LE, 12,000 scans per charge, IP65'
        ],
        assessment: 'The Munich-based Workaround GmbH has brought the first industrial wearables onto the market with the ProGlove series. The handheld scanners are particularly suitable for processes with high scanning frequencies. A laser target makes it easier to capture barcodes. The MARK 3 can be operated separately or used together with Android or iOS mobile devices.',
        manufacturer_url: 'https://www.proglove.com/de/produkte/wearable-scanners/mark-3/',
    },
    {
        id: "c95fab73-ee3a-4bcc-a960-d840f0d52b1f",
        is_favorite: false,
        is_rental: false,
        type: 'HANDHELD_COMPUTER',
        manufacturer: 'DATALOGIC',
        operational_area: [
            { label: 'Warehouse & Production', value: 'WAREHOUSE_&_PRODUCTION' },
            { label: 'Field Service', value: 'FIELD_SERVICE' }
        ],
        price: 1200,
        weight: 295,
        name: 'Datalogic Memor 20',
        image: 'https://skystatic08.atmos.id/11018/2049634327/2025004846/2012441964/datalogic_memor20@2x.jpg',
        specifications: [
            'Price: from 1200 euros',
            'Display: 5.7 inches',
            'Weight: 295 grams',
            'Available accessories: removable battery and wireless charging (WPC QI EPP), chemical-resistant plastic housing'
        ],
        assessment: 'The Memor 20 is the manufacturer\'s most robust industrial handheld. It is IP65 and 67 certified and is suitable for use in harsh conditions. Thanks to LTE support with 2 SIM card slots, it can be used in field service. The scanning engine enables close-range scanning. It is intended for use between -20 and 50° Celsius.',
        manufacturer_url: 'https://www.datalogic.com/deu/einzelhandel-industrielle-automation-transport-logistik-gesundheitswesen/mobilcomputer/memor-20-pd-869.html',
    },
    {
        id: "03044a6c-e293-4337-8838-98f538af2c96",
        is_favorite: false,
        is_rental: false,
        type: 'HANDHELD_COMPUTER',
        manufacturer: 'DATALOGIC',
        operational_area: [
            { label: 'Healthcare', value: 'HEALTHCARE' }, 
        ],
        price: 950,
        weight: 285,
        name: 'Datalogic Memor 10 Healthcare',
        image: 'https://skystatic08.atmos.id/11018/2049634327/2028350172/2012441964/datalogic_memor10_healthcare@2x.jpg',
        specifications: [
            'Price: from 950 euros',
            'Display: 5 inches',
            'Weight: 285 grams',
            'Available accessories: 1D/2D imager with Green Spot technology (visual scan confirmation), contactless charging possible - replaceable battery'
        ],
        assessment: 'The Memor 10 in the healthcare version is a high-performance device for healthcare applications. The technical parameters are convincing, the device is delivered with Android 8.1. It is resistant to disinfectants and IP65 certified.',
        manufacturer_url: 'https://www.datalogic.com/deu/einzelhandel-industrielle-automation-transport-logistik-gesundheitswesen/mobilcomputer/memor-10-pd-838.html',
    },
    {
        id: "5e357dd9-3846-4fe7-b8d4-391a9b9a1b3a",
        is_favorite: false,
        is_rental: false,
        type: 'HANDHELD_COMPUTER',
        manufacturer: 'CASIO',
        operational_area: [
            { label: 'Warehouse & Production', value: 'WAREHOUSE_&_PRODUCTION' }
        ],
        price: 1500,
        weight: 300,
        name: 'Casio IT-G600 / IT-G650',
        image: 'https://skystatic08.atmos.id/11018/2049634327/2030145514/2012441964/Casio IT G600_650.png',
        specifications: [
            'Price: from 1500 euros',
            'Display: 5.5 inches',
            'Weight: 300 grams',
            'Available accessories: 25° inclined scanning unit, LTE, Bluetooth, WLAN, NFC, choice between 4.7 and 5.5 inches'
        ],
        assessment: 'The IT-G6xx devices form Casio\'s flagship series. The IT-G600 has a physical 10-key keyboard, the IT-G650 is the full-touch alternative. Both model variants have high-performance features and Android 9 as the operating system. The inclined scanning ergonomics distinguish the device from other devices in its class.',
        manufacturer_url: 'https://www.mobile-barcode-scanner.com/de/produkte/it-g600-it-g650/',
    },
    {
        id: "5d06823a-8e6e-4e98-80e3-99301858b1ab",
        is_favorite: false,
        is_rental: false,
        type: 'HANDHELD_COMPUTER',
        manufacturer: 'POINT_MOBILE',
        operational_area: [
            { label: 'Warehouse & Production', value: 'WAREHOUSE_&_PRODUCTION' },
            { label: 'Field Service', value: 'FIELD_SERVICE' }
        ],
        price: 1000,
        weight: 602,
        name: 'Point Mobile PM560',
        image: 'https://skystatic08.atmos.id/11018/2049634327/2034482939/2012441964/Point Mobile PM560.png',
        specifications: [
            'Price: from 1000 euros',
            'Display: 4.3 inches',
            'Weight: 602 grams',
            'Available accessories: 1D/2D imager (3 options) / optional N6803 FR up to 10 m range, numeric or alphanumeric keyboard, upgradeable to Android 14, WIFI-6, 6300 mAh battery, 1.8 m drop resistant, IP65'
        ],
        assessment: 'A classic handheld for warehouse logistics with a good price-performance ratio. Honeywell supplies the scan engine, and the physical keyboard complements the operation on the touchscreen. Numerous useful software tools are supplied ex works.',
        manufacturer_url: 'https://www.pointmobile.com/en/products-handheldterminal/PM560',
    },
    {
        id: "48d0b5ff-9609-44ef-83f7-44a907104a87",
        is_favorite: false,
        is_rental: false,
        type: 'SMARTPHONE',
        manufacturer: 'GIGASET',
        operational_area: [
            { label: 'Beverage Logistics', value: 'BEVERAGE_LOGISTICS' },
        ],
        price: 250,
        weight: 287,
        name: 'Gigaset GX290 Plus',
        image: 'https://skystatic08.atmos.id/11018/2049634327/2035087401/2012441964/Gigaset GX290 plus.png',
        specifications: [
            'Price: from 250 euros',
            'Display: 6.1 inches',
            'Weight: 287 grams',
            'Available accessories: IP68, Military Standard 810G, 6200 mAh battery'
        ],
        assessment: 'The Gigaset GX290 is a cost-effective and robust smartphone that can withstand any external influences and impresses with its modern design. Thanks to the large battery, it is also very suitable for longer shifts and tours.',
        manufacturer_url: 'https://www.gigaset.com/de_de//',
    },
    {
        id: "4622c291-27c2-4d7b-ace7-11861df9fe32",
        is_favorite: true,
        is_rental: false,
        type: 'HANDHELD_COMPUTER',
        manufacturer: 'HONEYWELL',
        operational_area: [
            { label: 'Warehouse & Production', value: 'WAREHOUSE_&_PRODUCTION' },
            { label: 'Explosion-proof', value: 'EXPLOSION_PROOF' },
        ],
        price: 1200,
        weight: 498,
        name: 'Honeywell Dolphin CK65',
        image: 'https://skystatic08.atmos.id/11018/2049634327/2035734119/2012441964/Honeywell Dolphin CK65.png',
        specifications: [
            'Price: from 1200 euros',
            'Display: 4 inches',
            'Weight: 498 grams',
            'Available accessories: various scanner options with a range of up to 24 m, up to 95%, non-condensing, fall resistance up to 3 m, models for refrigerated and hazardous areas, upgradeable to Android 12'
        ],
        assessment: 'The CK65 is Honeywell\'s powerful all-round device for use in warehouse logistics. With the EX20 Near/Far Imager, employees can capture barcodes from a distance of 15 cm to 15 meters. The 7000 mAh battery provides a continuous operating time of approximately 28 hours per charge.',
        manufacturer_url: 'https://sps.honeywell.com/de/de/products/productivity/mobile-computers/handheld-computers/ck65-handheld-computer',
    },
    {
        id: "57fdf5d8-b82e-40b5-b428-783feb59a69f",
        is_favorite: false,
        is_rental: false,
        type: 'SMARTPHONE',
        manufacturer: 'CAT',
        operational_area: [
            { label: 'Beverage Logistics', value: 'BEVERAGE_LOGISTICS' },
            { label: 'Healthcare', value: 'HEALTHCARE' }, 
        ],
        price: 480,
        weight: 268,
        name: 'CAT S75',
        image: 'https://skystatic08.atmos.id/11018/2049634327/2036388291/2012441964/CAT S75.png',
        specifications: [
            'Price: from 480 euros',
            'Display: 6.58 inches',
            'Weight: 268 grams',
            'Available accessories: Android 12 (up to 14), IP69k, fixed 5000 mAh battery, waterproof at 5 m for 35 min, 1.8 m drop resistance'
        ],
        assessment: 'The CAT S75 is a large, slim outdoor smartphone that combines modern design and robustness. It can be used in the healthcare sector due to its resistance to disinfectants and other intensive cleaning.',
        manufacturer_url: 'https://www.catphones.com/de-de/cat-s75/',
    },
    {
        id: "54bc5d85-3946-4f5e-9fae-1ebe9c3dec5f",
        is_favorite: false,
        is_rental: false,
        type: 'HANDHELD_COMPUTER',
        manufacturer: 'HONEYWELL',
        operational_area: [
            { label: 'Healthcare', value: 'HEALTHCARE' }, 
        ],
        price: 600,
        weight: 257,
        name: 'Honeywell ScanPal EDA52 HC',
        image: 'https://skystatic08.atmos.id/11018/2049634327/2036806814/2012441964/Honeywell EDA52HC.png',
        specifications: [
            'Price: from 600 euros',
            'Display: 5.5 inches',
            'Weight: 257 grams',
            'Available accessories: Scanner: N3601 and N6603 slim imager (1D and 2D barcodes), non-condensing, upgradable to Android 13, LTE, 4500 mAh battery, IP 67, USB-C'
        ],
        assessment: 'With the slim ScanPal EDA52 HC, Honeywell offers an affordable device for use in healthcare. The service life is designed for 3 years. According to the manufacturer, the EDA52 is resistant to disinfection during this time.',
        manufacturer_url: 'https://sps.honeywell.com/gb/en/products/productivity/mobile-computers/healthcare-computers/scanpal-eda52-healthcare-mobile-computer',
    },
    {
        id: "e26930d1-6046-475c-84eb-e89e9edad523",
        is_favorite: false,
        is_rental: false,
        type: 'WEARABLE_HANDHELD_SCANNER',
        manufacturer: 'PROGLOVE',
        operational_area: [
            { label: 'Warehouse & Production', value: 'WAREHOUSE_&_PRODUCTION' }
        ],
        price: 1300,
        weight: 48,
        name: 'ProGlove MARK display',
        image: 'https://skystatic08.atmos.id/11018/2049634327/2038365215/2012441964/ProGlove Mark Display.png',
        specifications: [
            'Price: from 1300 euros',
            'Display: 1.54 inches',
            'Weight: 48 grams',
            'Available accessories: 1D/2D imager, 30 to 150 cm scanning range, high-contrast e-paper display, Bluetooth Low Energy 5.0'
        ],
        assessment: 'Work processes in industrial environments, in transport and logistics or even in retail can be made significantly easier with the help of practical data capture. Simple operation with clear feedback and working with your hands free enable faster operational processes, e.g. B. in picking.',
        manufacturer_url: 'https://www.proglove.com/products/wearable-scanners/mark-display/#product-contact',
    },
    {
        id: "c968faa9-0d33-4e1b-a3a7-004d42211ce0",
        is_favorite: false,
        is_rental: false,
        type: 'HANDHELD_COMPUTER',
        manufacturer: 'DATALOGIC',
        operational_area: [
            { label: 'Beverage Logistics', value: 'BEVERAGE_LOGISTICS' },
            { label: 'Warehouse & Production', value: 'WAREHOUSE_&_PRODUCTION' }
        ],
        price: 600,
        weight: 268,
        name: 'Datalogic Memor K',
        image: 'https://skystatic08.atmos.id/11018/2049634327/2038742226/2012441964/Datalogic Memor K.png',
        specifications: [
            'Price: from 600 euros',
            'Display: 4 inches',
            'Weight: 268 grams',
            'Available accessories: Simple 1D/2D scan engines and removable battery with 3,800 mAh'
        ],
        assessment: 'With the Memor K, Datalogic offers a comparatively small industrial handheld to support mobile processes in warehouse, production or delivery logistics. A physical keyboard with 24 keys complements operation via the touchscreen.',
        manufacturer_url: 'https://www.datalogic.com/deu/industrielle-automation-transport-logistik/mobilcomputer/memor-k-pd-876.html',
    },
    {
        id: "d1e98fec-cd69-4356-b795-ac820230f794",
        is_favorite: false,
        is_rental: false,
        type: 'FORKLIFT_TERMINAL_TABLET',
        manufacturer: 'PANASONIC',
        operational_area: [
            { label: 'Maintenance', value: 'MAINTENANCE' },
            { label: 'Warehouse & Production', value: 'WAREHOUSE_&_PRODUCTION' }, 
            { label: 'Field Service', value: 'FIELD_SERVICE' },         
        ],
        price: 950,
        weight: 510,
        name: 'Panasonic Toughbook S1',
        image: 'https://skystatic08.atmos.id/11018/2049634327/2038944939/2012441964/Panasonic Toughbook S1.png',
        specifications: [
            'Price: from 950 euros',
            'Display: 7 inches',
            'Weight: 510 grams',
            'Available accessories: spare battery (5580 mAh), flat additional battery (3200 mAh), 5-slot battery charger, various hand strap and carrying solutions, desktop charging station, vehicle dock, passive stylus, etc.'
        ],
        assessment: 'The Toughbook S1 from Panasonic is a modern and extremely robust tablet computer. It is therefore well suited for industrial environments and field use. The battery is its clear strength, as it lasts up to 14 hours and can be quickly replaced with a replacement battery.',
        manufacturer_url: 'https://business.panasonic.de/mobile-it-solutions/produkte-und-zubeh%C3%B6r/tablets/TOUGHBOOK-S1',
    },
    {
        id: "2f6e763c-602f-41d7-9a4e-443fc2673c1c",
        is_favorite: true,
        is_rental: false,
        type: 'HANDHELD_COMPUTER',
        manufacturer: 'HONEYWELL',
        operational_area: [
            { label: 'Warehouse & Production', value: 'WAREHOUSE_&_PRODUCTION' }, 
            { label: 'Field Service', value: 'FIELD_SERVICE' },         
        ],
        price: 1200,
        weight: 360,
        name: 'Honeywell Dolphin CT60 XP',
        image: 'https://skystatic08.atmos.id/11018/2049634327/2039480267/2012441964/honeywell_dolphin_ct60@2x.png',
        specifications: [
            'Price: from 1200 euros',
            'Display: 4.7 inches',
            'Weight: 360 grams',
            'Available accessories: Imager for scanning 1D and 2D barcodes, extensive accessories, e.g. B. well designed pistol grip available'
        ],
        assessment: 'Very good value for money in the middle class. The device impresses with a precise scanner, a fast processor and high-quality workmanship.',
        manufacturer_url: 'https://sps.honeywell.com/de/de/products/productivity/mobile-computers/handheld-computers/ct60-xp-handheld-computer',
    },
    {
        id: "61742430-7de8-4457-a0a2-2395e06421c5",
        is_favorite: true,
        is_rental: false,
        type: 'HANDHELD_COMPUTER',
        manufacturer: 'KEYENCE',
        operational_area: [
            { label: 'Warehouse & Production', value: 'WAREHOUSE_&_PRODUCTION' }, 
        ],
        price: 0,
        weight: 487,
        name: 'Keyence BT-A700',
        image: 'https://skystatic08.atmos.id/11018/2049634327/2041705648/2012441964/Keyence BT-A700.png',
        specifications: [
            'Price: from 0 euros',
            'Display: 5 inches',
            'Weight: 487 grams',
            'Available accessories: Full-range scanning engine: 2.5 cm - 10 m scanning range, replaceable 6250 mAh battery, emergency power supply, one-handed operation, IP67'
        ],
        assessment: 'The BT-A700 is a very high-quality mobile computer from the Japanese sensor specialist Keyence. The handheld terminal therefore has a high-performance scan engine. In addition to its robustness, the device impresses with its low weight and a very powerful battery.',
        manufacturer_url: 'https://www.keyence.de/products/mobile-computers/handheld-computers/bt-a700/',
    },
    {
        id: "2e76f13a-0d48-49f1-8a40-19d20ffdbd82",
        is_favorite: false,
        is_rental: false,
        type: 'WEARABLE_HANDHELD_SCANNER',
        manufacturer: 'FEIG',
        operational_area: [
            { label: 'Warehouse & Production', value: 'WAREHOUSE_&_PRODUCTION' }, 
        ],
        price: 600,
        weight: 70,
        name: 'Feig HyWEAR compact xT',
        image: 'https://skystatic08.atmos.id/11018/2049634327/2043918401/2012441964/Feig HyWear compact xT.png',
        specifications: [
            'Price: from 600 euros',
            'Display: 0 inches',
            'Weight: 70 grams',
            'Available accessories: replaceable 1100mAh battery, BT 5.0, 4-way charging station, 2 configurable function keys, different work gloves, WLAN, 2D imager extended range'
        ],
        assessment: 'HyWEAR compact is a hybrid barcode & RFID (optional) wearable that makes logistical processes more efficient by working with both hands and offers a good alternative to the Proglove hand scanner.',
        manufacturer_url: 'https://www.feig.de/produkte/identification/produkt/hywear-compact-xt/',
    },
    {
        id: "5170dd7b-9e91-4921-823e-b2a8ad06927f",
        is_favorite: false,
        is_rental: false,
        type: 'FORKLIFT_TERMINAL_TABLET',
        manufacturer: 'PANASONIC',
        operational_area: [
            { label: 'Maintenance', value: 'MAINTENANCE' },
            { label: 'Field Service', value: 'FIELD_SERVICE' }
        ],
        price: 1500,
        weight: 885,
        name: 'Panasonic Toughbook A3',
        image: 'https://skystatic08.atmos.id/11018/2049634327/2043949983/2012441964/panasonic_fz-a3@2x.jpg',
        specifications: [
            'Price: from 1500 euros',
            'Display: 10.1 inches',
            'Weight: 885 grams',
            'Available accessories: Extra long operating time of up to 15 hours with additional battery, LTE, Bluetooth, WLAN, NFC + gadget port'
        ],
        assessment: 'With the FZ-A3, Panasonic delivers a high-performance and very robust tablet for outdoor use. The anti-reflective screen is very easy to read outdoors. The optional use of a scanner or smart card reader makes the device very flexible. It is also suitable for use on forklifts.',
        manufacturer_url: 'https://business.panasonic.de/mobile-it-solutions/produkte-und-zubeh%C3%B6r/tablets/TOUGHBOOK-A3',
    },
    {
        id: "1ab07733-f92a-4ce0-bde4-1e0865bb776b",
        is_favorite: false,
        is_rental: false,
        type: 'HANDHELD_COMPUTER',
        manufacturer: 'ZEBRA',
        operational_area: [
            { label: 'Warehouse & Production', value: 'WAREHOUSE_&_PRODUCTION' }, 
        ],
        price: 2000,
        weight: 490,
        name: 'Zebra TC8300',
        image: 'https://skystatic08.atmos.id/11018/2049634327/2044520301/2012441964/zebra_tc8300@2x.jpg',
        specifications: [
            'Price: from 2000 euros',
            'Display: 4 inches',
            'Weight: 490 grams',
            'Available accessories: Inclined scanning angle and pistol grip form factor, 5 scan engines for scanning from 3" to 70 feet'
        ],
        assessment: 'An innovative design with an inclined barcode scanner makes the TC8300 from Zebra an exceptional device. The current version has a fast processor and a powerful 7,000 mAh battery.',
        manufacturer_url: 'https://www.zebra.com/de/de/products/mobile-computers/handheld/tc8300.html',
    },
    {
        id: "a82d31ca-b46c-430b-bd96-4c042b62b335",
        is_favorite: false,
        is_rental: false,
        type: 'HANDHELD_COMPUTER',
        manufacturer: 'ZEBRA',
        operational_area: [
            { label: 'Warehouse & Production', value: 'WAREHOUSE_&_PRODUCTION' }, 
        ],
        price: 1900,
        weight: 765,
        name: 'Zebra MC9300',
        image: 'https://skystatic08.atmos.id/11018/2049634327/2051671743/2012441964/zebra mc9300.png',
        specifications: [
            'Price: from 1900 euros',
            'Display: 4.3 inches',
            'Weight: 765 grams',
            'Available accessories: 4 scan engines (omnidirectional, DPM, long-range), powerful 7,000 mAh battery'
        ],
        assessment: 'The MC9300 is a very robust device. Various configurations enable precise use in harsh environments. Unfortunately, Zebra does not offer a mobile phone option, which would make the device the ideal terminal in the external warehouse.',
        manufacturer_url: 'https://www.zebra.com/de/de/products/mobile-computers/handheld/mc9300.html',
    },
    {
        id: "7f0e8d78-22bd-4f99-96a2-1a980c76f9a1",
        is_favorite: false,
        is_rental: false,
        type: 'SMARTPHONE',
        manufacturer: 'I_SAFE_MOBILE',
        operational_area: [
            { label: 'Beverage Logistics', value: 'BEVERAGE_LOGISTICS' },
            { label: 'Warehouse & Production', value: 'WAREHOUSE_&_PRODUCTION' }, 
            { label: 'Explosion-proof', value: 'EXPLOSION_PROOF' },
        ],
        price: 650,
        weight: 203,
        name: 'i.Safe Mobile IS655.2',
        image: 'https://skystatic08.atmos.id/11018/2049634327/2052054549/2012441964/i.safe IS655.2.png',
        specifications: [
            'Price: from 650 euros',
            'Display: 5.5 inches',
            'Weight: 203 grams',
            'Available accessories: IP68, 13MP front and 8MP back camera, BT 5.0, integrated 4200mAh battery, LTE, 5Ghz Wifi'
        ],
        assessment: 'The specialist for explosion-proof industrial devices i.Safe Mobile now also has a smartphone device. This is suitable for use in delivery, especially in the chemical sector, and has protection for explosion zone 2.',
        manufacturer_url: 'https://www.isafe-mobile.com/de/produkte/produkte-zone-2/22/is6552',
    },
    {
        id: "95842978-6017-44f8-89f4-9411a96c81a7",
        is_favorite: true,
        is_rental: false,
        type: 'PRINTER',
        manufacturer: 'ZEBRA',
        operational_area: [
            { label: 'Beverage Logistics', value: 'BEVERAGE_LOGISTICS' },
            { label: 'Maintenance', value: 'MAINTENANCE' },
            { label: 'Warehouse & Production', value: 'WAREHOUSE_&_PRODUCTION' }, 
            { label: 'Field Service', value: 'FIELD_SERVICE' }, 
        ],
        price: 650,
        weight: 790,
        name: 'Zebra ZQ521',
        image: 'https://skystatic08.atmos.id/11018/2049634327/2052768094/2012441964/Zebra ZQ521.png',
        specifications: [
            'Price: from 650 euros',
            'Display: 4 inches',
            'Weight: 790 grams',
            'Available accessories: IP54 certified - Exoskeleton available and prints labels, direct thermal and RFID labels, BT 4.1 + BT Low Energy.'
        ],
        assessment: 'The ZQ521 is the latest model in Zebra\'s ZQ series. In addition to classic receipt and label printing, according to Zebra, the ZQ521 is the only 4-inch printer on the market that can also print RFID labels. Zebra has improved some performance metrics, including battery and internal storage capacity. The latest Bluetooth standard is also supported.',
        manufacturer_url: 'https://www.zebra.com/de/de/products/spec-sheets/printers/mobile/zq511-zq521.html',
    },
    {
        id: "6332f5a3-bf55-4b27-82d9-28f63e47e0f4",
        is_favorite: false,
        is_rental: false,
        type: 'HANDHELD_COMPUTER',
        manufacturer: 'POINT_MOBILE',
        operational_area: [
            { label: 'Warehouse & Production', value: 'WAREHOUSE_&_PRODUCTION' }, 
        ],
        price: 600,
        weight: 320,
        name: 'Point Mobile PM351',
        image: 'https://skystatic08.atmos.id/11018/2049634327/2053890576/2012441964/PM351.png',
        specifications: [
            'Price: from 600 euros',
            'Display: 4 inches',
            'Weight: 320 grams',
            'Available accessories: 1D/2D imager, LTE optional, upgradeable to Android 14, Wi-Fi 6, 1.5 m drop protection, IP65, 4800 mAh battery, BT 5.1'
        ],
        assessment: 'The Point Mobile PM351 is a compact, affordable mobile computer. Scanner, keyboard and LTE capability can be selected appropriately. Accessories such as a pistol grip are available.',
        manufacturer_url: 'https://www.pointmobile.com/de/products-handheldterminal/PM351',
    },
    {
        id: "8b5262f9-2b3c-4969-9c36-f42a602934f7",
        is_favorite: false,
        is_rental: false,
        type: 'HANDHELD_COMPUTER',
        manufacturer: 'POINT_MOBILE',
        operational_area: [
            { label: 'Beverage Logistics', value: 'BEVERAGE_LOGISTICS' }, 
            { label: 'Warehouse & Production', value: 'WAREHOUSE_&_PRODUCTION' }, 
        ],
        price: 1200,
        weight: 287,
        name: 'Point Mobile PM86',
        image: 'https://skystatic08.atmos.id/11018/2049634327/2053950471/2012441964/Point Mobile Pm86.png',
        specifications: [
            'Price: from 1200 euros',
            'Display: 5 inches',
            'Weight: 287 grams',
            'Available accessories: 1D/2D barcode scanner N3603, N6703, N6803 FR (10m range), IP67, WIFI 6, LTE, Android 11 (upgradable to 14), 4080 mAh battery, optional extended 5800 mAh battery, 1.5m fall resistance'
        ],
        assessment: 'Compared to its predecessor, the PM86 is identical to Point Mobile\'s PM85 and is equipped with new hardware and a larger battery. It is possible to choose between 3 scan engines with optionally extended range. As with its predecessor, the bright display is positive here.',
        manufacturer_url: 'https://www.pointmobile.com/en/products-mobilecomputers/PM86',
    },
    {
        id: "e16ffa97-d0dd-4590-b4e2-4c0c3f9e2ffc",
        is_favorite: false,
        is_rental: false,
        type: 'FORKLIFT_TERMINAL_TABLET',
        manufacturer: 'ZEBRA',
        operational_area: [
            { label: 'Maintenance', value: 'MAINTENANCE' },
            { label: 'Warehouse & Production', value: 'WAREHOUSE_&_PRODUCTION' }, 
            { label: 'Field Service', value: 'FIELD_SERVICE' }, 
        ],
        price: 1350,
        weight: 1074,
        name: 'Zebra ET60/ET65 tablet',
        image: 'https://skystatic08.atmos.id/11018/2049634327/2055003499/2012441964/Zebra ET60.png',
        specifications: [
            'Price: from 1350 euros',
            'Display: 10.1 inches',
            'Weight: 1074 grams',
            'Available accessories: Keyboard option, vehicle dock option, scanner option (SE55 Long-Range), LTE (ET65), upgradeable to Android 16, drop resistance up to 1.5 m, Freezer model with integrated heater, IP66, 8920 mAh or 17840 mAh battery'
        ],
        assessment: 'The new ET60 series from Zebra can be used as a vehicle terminal or mobile computer with a removable keyboard. The ET60 or ET65 (with LTE) can be used in a temperature range from -30°C to +60°C. In the Freezer version with a heated screen, working at humidity of up to 95% is possible.',
        manufacturer_url: 'https://www.zebra.com/us/en/products/spec-sheets/tablets/et60-et65.html',
    },
];

export default products;
