import { Roboto } from "next/font/google";
import "./globals.css";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";

const inter = Roboto({ 
  subsets: ["latin"], 
    weight: ['400', '700'],

});
config.autoAddCss = false;

export const metadata = {
  title: "Ontego Hardware Finder",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
